language: php

sudo: false

matrix:
  allow_failures:
    - php: 7.0
  include:
    - php: 5.2
      env: WP_VERSION=4.7 WP_MULTISITE=1 PHPLINT=1
    - php: 5.2
      env: WP_VERSION=4.7
    - php: 5.2
      env: WP_VERSION=4.6
    - php: 5.2
      env: WP_VERSION=4.5
    - php: 5.2
      env: WP_VERSION=4.4
    - php: 7.0
      env: WP_VERSION=4.7 COVERAGE=1

dist: precise

before_script:
- phpenv local --unset
- PLUGIN_SLUG=$(basename $(pwd))
- export WP_DEVELOP_DIR=/tmp/wordpress/
- git clone --depth=50 --branch="$WP_VERSION" git://develop.git.wordpress.org/ /tmp/wordpress
- cd ..
- cp -r "$PLUGIN_SLUG" "/tmp/wordpress/src/wp-content/plugins/$PLUGIN_SLUG"
- cd /tmp/wordpress/
- cp wp-tests-config-sample.php wp-tests-config.php
- sed -i "s/youremptytestdbnamehere/wordpress_tests/" wp-tests-config.php
- sed -i "s/yourusernamehere/travis/" wp-tests-config.php
- sed -i "s/yourpasswordhere//" wp-tests-config.php
- mysql -e "CREATE DATABASE wordpress_tests;" -uroot
- cd "/tmp/wordpress/src/wp-content/plugins/$PLUGIN_SLUG"
- phpenv rehash

script:
- if [[ "$COVERAGE" == "1" ]]; then phpunit -c tests/phpunit.xml --coverage-clover build/logs/clover.xml; else phpunit -c tests/phpunit.xml; fi

notifications:
    email:
        on_success: never
        on_failure: never
